In [1]:
import pandas as pd
import selenium
from selenium import webdriver
from selenium.common.exceptions import ElementNotInteractableException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.chrome.options import Options
import time

##### 1. Scrape the details of most viewed videos on YouTube from Wikipedia.

In [2]:
# Function Definition
def youtube(url):
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating the empty lists for  the data to be extracted.
    rank = []
    name = []
    artist = []
    upload_date = []
    views = []
    list_of_data = [rank, name, artist, upload_date, views]
    
    # Extracting the required data.
    for x in range(1,6):
        for i in driver.find_elements_by_xpath("//tbody/tr/td[" + str(x) + "]")[:30]:
            list_of_data[x-1].append(i.text)
    
    # striping the extra data from name.
    duplicate_name = []
    for n in list_of_data[1]:
        duplicate_name.append(n[:-4])
        
    list_of_data[1] = duplicate_name
    
    # Creating the dataframe.
    most_watched  =  pd.DataFrame({"Rank" : list_of_data[0],
                                  "Name" : list_of_data[1],
                                  "Artist" : list_of_data[2],
                                  "Upload Date" : list_of_data[3],
                                  "Views" : list_of_data[4]})
    return most_watched
    
    
# calling function
youtube("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""",Pinkfong Kids' Songs & Stories,7.39,"June 17, 2016"
1,2.,"""Despacito""",Luis Fonsi featuring Daddy Yankee,7.09,"January 12, 2017"
2,3.,"""Shape of You""",Ed Sheeran,5.10,"January 30, 2017"
3,4.,"""See You Again""",Wiz Khalifa featuring Charlie Puth,4.85,"April 6, 2015"
4,5.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.38,"January 31, 2012"
5,6.,"""Johny Johny Yes Papa""",LooLoo Kids,4.37,"October 8, 2016"
6,7.,"""Uptown Funk""",Mark Ronson featuring Bruno Mars,4.03,"November 19, 2014"
7,8.,"""Gangnam Style""",Psy,3.88,"July 15, 2012"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,3.66,"February 27, 2018"
9,10.,"""Sorry""",Justin Bieber,3.37,"October 22, 2015"
10,11.,"""Bath Song""",Cocomelon – Nursery Rhymes,3.34,"May 2, 2018"
11,12.,"""Sugar""",Maroon 5,3.34,"January 14, 2015"
12,13.,"""Phonics Song with Two Words""",ChuChu TV,3.30,"March 6, 2014"
13,14.,"""Roar""",Katy Perry,3.22,"September 5, 2013"
14,15.,"""Thinking Out Loud""",Ed Sheeran,3.13,"October 7, 2014"
15,16.,"""Counting Stars""",OneRepublic,3.13,"May 31, 2013"
16,17.,"""Shake It Off""",Taylor Swift,2.99,"August 18, 2014"
17,18.,"""Dame Tu Cosita""",El Chombo featuring Cutty Ranks,2.94,"April 5, 2018"
18,19.,"""Bailando""",Enrique Iglesias featuring Descemer Bueno and ...,2.94,"April 11, 2014"
19,20.,"""Lean On""",Major Lazer and DJ Snake featuring MØ,2.93,"March 22, 2015"
20,21.,"""Faded""",Alan Walker,2.92,"December 3, 2015"
21,22.,"""Dark Horse""",Katy Perry featuring Juicy J,2.92,"February 20, 2014"
22,23.,"""Girls Like You""",Maroon 5 featuring Cardi B,2.91,"May 31, 2018"
23,24.,"""Let Her Go""",Passenger,2.85,"July 25, 2012"
24,25.,"""Mi Gente""",J Balvin and Willy William,2.82,"June 29, 2017"
25,26.,"""Hello""",Adele,2.75,"October 22, 2015"
26,27.,"""Blank Space""",Taylor Swift,2.68,"November 10, 2014"
27,28.,"""Waka Waka (This Time for Africa)""",Shakira featuring Freshlyground,2.66,"June 4, 2010"
28,29.,"""Perfect""",Ed Sheeran,2.65,"November 9, 2017"
29,30.,"""Chantaje""",Shakira featuring Maluma,2.60,"November 18, 2016"

##### 2. Scrape the details team India’s international fixtures from bcci.tv.

In [3]:
def bcci(url):
    chrome_options = Options()
    chrome_options.add_argument('--incognito')
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating the empty lists for  the data to be extracted.
    match_title = []
    series = []
    place = []
    match_date = []
    match_month = []
    date = []
    time = []
    
    # Reaching to the international
    driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']").click()
    
    # Reaching Fixtures
    try:
        fix = driver.find_element_by_xpath("//ul[@class = 'navigation__list showMoreEnabled']/li[1]/div[2]/div/ul/li[1]/a")
        fix.click()
    except ElementNotInteractableException as e:
        driver.get(fix.get_attribute('href'))
        
    # Extracting data
    # Match Title
    for i in driver.find_elements_by_xpath("//span[@class = 'u-unskewed-text fixture__tournament-label u-truncated']"):
        match_title.append(i.text)
   
    # Place
    for i in driver.find_elements_by_xpath("//p[@class = 'fixture__additional-info']/span"):
        place.append(i.text)
    # Date
    for i in driver.find_elements_by_xpath("//span[@class = 'fixture__date']"):
        match_date.append(i.text)
    for i in driver.find_elements_by_xpath("//span[@class = 'fixture__month']"):
        match_month.append(i.text)
    for i in range(len(match_date)):
        date.append(match_date[i] + " " + match_month[i])
    # Time
    for i in driver.find_elements_by_xpath("//span[@class ='fixture__time']"):
        time.append(i.text)
        
    # Series
    try:
        element = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
        for i in element:
            series.append(i.text)
    except StaleElementReferenceException as e:
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'fixture__name fixture__name--with-margin')))
        element = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
        for i in element:
            series.append(i.text)
        
    # Creating dataframe
    intl_df = pd.DataFrame({"Match Title" : match_title,
                            "Series" : series,
                            "Place" : place,
                            "Date" : date,
                            "Time" : time})
    return intl_df


# Calling Function
bcci("https://www.bcci.tv/")

##### 3. Scrape the details of selenium exception from guru99.com.

In [3]:
# Function Definition
def guru(url):
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Reaching to the selenium exceptions handling page.
    driver.find_element_by_xpath("//a[@title = 'Selenium']").click()
    driver.find_element_by_xpath("//a[@title = 'Selenium Exception Handling (Common Exceptions List)']").click()
    
    # Creating the empty lists for  the data to be extracted.
    name = []
    description = []
    data_list = [name, description]
    
    # Extrating required data
    for x in range(1,3):
        for i in driver.find_elements_by_xpath("//table[@class = 'table table-striped']/tbody/tr/td[" + str(x) + "]")[1:42]:
            data_list[x-1].append(i.text)
            
    # Creating dataframe.
    exception_df = pd.DataFrame({"Name" : data_list[0],
                            "Description" : data_list[1]})
    return exception_df


# Calling function
guru("https://www.guru99.com/")

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

##### 4. Scrape the details of State-wise GDP of India from statisticstime.com.

In [4]:
# Function Definition
def economy(url):
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating the empty lists for  the data to be extracted.
    rank = []
    state = []
    GSDP_18_19 = []
    GSDP_17_18 = []
    share = []
    GDP = []
    
    list_of_data = [GSDP_18_19, share, GDP]
    
    # Reaching to the economy option.
    driver.find_element_by_xpath("//div[@class = 'navbar']/div[2]/button").click()
    
    # Reaching India page.+9999
    try:
        india = driver.find_element_by_xpath("//div[@class = 'navbar']/div[2]/div/a[2]")
        india.click()
    except ElementNotInteractableException as e:
        driver.get(india.get_attribute('href'))
        
    # Reaching to the state wise GDP page.
    driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a").click()
    
    # Extracting required data.
    # Rank
    for i in driver.find_elements_by_xpath("//table[@id = 'table_id']/tbody/tr/td[@class = 'data1']"):
        rank.append(i.text)
    # State
    for i in driver.find_elements_by_xpath("//table[@id = 'table_id']/tbody/tr/td[@class = 'name']"):
        state.append(i.text)
    # GSDP_17_18
    for i in driver.find_elements_by_xpath("//table[@id = 'table_id']/tbody/tr/td[@class = 'data sorting_1']"):
        GSDP_17_18.append(i.text)
    # GSDP_18_19, share, GDP
    for x in range(1,4):
        for i in driver.find_elements_by_xpath("//table[@id = 'table_id']/tbody/tr/td[@class = 'data'][" + str(x) + "]"):
            list_of_data[x-1].append(i.text)
            
    # Creating dataframe
    df_GDP  =  pd.DataFrame({"Rank" : rank,
                                  "State" : state,
                                  "GSDP (18-19)" : list_of_data[0],
                                  "GSDP (17-18)" : GSDP_17_18,
                                  "share" : list_of_data[1],
                                  "GDP" : list_of_data[2]})
    return df_GDP



# Calling Function
economy("http://statisticstimes.com/")

   Rank                      State GSDP (18-19) GSDP (17-18)   share      GDP
0     1                Maharashtra            -    2,411,600  14.11%  374.196
1     2                 Tamil Nadu    1,664,159    1,461,841   8.55%  226.827
2     3              Uttar Pradesh    1,542,432    1,376,324   8.05%  213.558
3     4                  Karnataka    1,535,224    1,350,257   7.90%  209.513
4     5                    Gujarat            -    1,314,680   7.69%  203.993
5     6                West Bengal    1,177,586      999,585   5.85%  155.101
6     7                  Rajasthan      929,124      835,558   4.89%  129.650
7     8             Andhra Pradesh      933,402      809,547   4.74%  125.614
8     9                  Telangana      865,688      753,811   4.41%  116.965
9    10             Madhya Pradesh      809,327      728,242   4.26%  112.998
10   11                     Kerala            -      700,532   4.10%  108.698
11   12                      Delhi      779,652      690,098   4.04%  107.079
12   13                    Haryana      707,126      626,054   3.66%   97.142
13   14                      Bihar      557,490      484,740   2.84%   75.215
14   15                     Punjab      521,861      479,141   2.80%   74.346
15   16                     Odisha      485,376      436,374   2.55%   67.710
16   17                      Assam            -      288,494   1.69%   44.764
17   18               Chhattisgarh      311,660      284,194   1.66%   44.097
18   19                  Jharkhand      307,581      276,243   1.62%   42.863
19   20                Uttarakhand      245,895      222,836   1.30%   34.576
20   21           Himachal Pradesh      153,181      140,613   0.82%   21.818
21   22            Jammu & Kashmir            -      138,488   0.81%   21.489
22   23                        Goa       77,172       70,493   0.41%   10.938
23   24                    Tripura            -       46,133   0.27%    7.158
24   25                 Chandigarh            -       38,806   0.23%    6.021
25   26                 Puducherry       36,656       32,962   0.19%    5.115
26   27                  Meghalaya            -       30,790   0.18%    4.778
27   28                   Nagaland            -       24,281   0.14%    3.768
28   29                    Manipur            -       23,968   0.14%    3.719
29   30                     Sikkim       26,786       23,495   0.14%    3.646
30   31          Arunachal Pradesh            -       22,045   0.13%    3.421
31   32                    Mizoram            -       19,457   0.11%    3.019
32   33  Andaman & Nicobar Islands            -        7,871   0.05%    1.221

##### 5. Scrape the details of trending repositories on Github.com.

In [2]:
# Function Defination
def github(url):
    ch_options = Options()
    ch_options.add_argument('--incognito')
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe", options = ch_options)
    driver.get(url)
    
    # Selecting Explore
    time.sleep(2)
    driver.find_element_by_xpath("//nav[@class = 'mt-0 px-3 px-lg-0 mb-5 mb-lg-0']/ul/li[4]").click()
    
    # Reaching to the trending page from dropdown
    time.sleep(2)
    try:
        trend = driver.find_element_by_xpath("//ul[@class = 'list-style-none mb-3'][2]/li[3]/a")
        trend.click()
    except ElementNotInteractableException:
        driver.get(trend.get_attribute('href'))
    
    # Creating empty lists for the data to be extracted.
    rep_title = []
    rep_description = []
    contri_count = []
    lang_used = []
    
    # Extracting the required data.
    # list of article
    all_items = driver.find_elements_by_xpath("//article[@class = 'Box-row']")
    # Repository Title
    for i in driver.find_elements_by_xpath("//article[@class = 'Box-row']/h1/a"):
        rep_title.append(i.text)
    # Contributors Count
    for i in driver.find_elements_by_xpath("//div[@class = 'f6 text-gray mt-2']/a[2]"):
        contri_count.append(i.text)
    # Repository Description and Language Used
    for i in all_items:
        try:
            rep_description.append(i.find_element_by_tag_name('p').text)
        except NoSuchElementException:
            rep_description.append("-") 
    
    # Creating the dataFrame
    trending_df = pd.DataFrame({"Repository Title" : rep_title,
                               "Repository Description" : rep_description,
                               "Contributors Count" : contri_count})
    return trending_df



# Calling Function
github("https://github.com/")

,Repository Title,Repository Description,Contributors Count
0,jwasham / coding-interview-university,A complete computer science study plan to beco...,"41,418"
1,sherlock-project / sherlock,🔎 Hunt down social media accounts by username ...,"1,889"
2,PeterL1n / BackgroundMattingV2,Real-Time High-Resolution Background Matting,58
3,hashicorp / packer,Packer is a tool for creating identical machin...,"3,030"
4,Azure / bicep,Bicep is a declarative language for describing...,107
5,stenzek / duckstation,Fast PlayStation 1 emulator for PC and Android,76
6,ggerganov / kbd-audio,Tools for capturing and analysing keyboard inp...,294
7,nvpro-samples / vk_mini_path_tracer,A beginner-friendly Vulkan path tracing tutori...,9
8,k0sproject / k0s,k0s - Zero Friction Kubernetes,103
9,aapatre / Automatic-Udemy-Course-Enroller-GET-...,Do you want to LEARN NEW STUFF for FREE? Don't...,212
10,microsoft / playwright,"Node.js library to automate Chromium, Firefox ...",750
11,google / mundane,Mundane is a Rust cryptography library backed ...,30
12,cloudquery / cloudquery,cloudquery transforms your cloud infrastructur...,26
13,googleprojectzero / Jackalope,"Binary, coverage-guided fuzzer for Windows and...",30
14,bambenek / research,-,23
15,ProlificLabs / shakesearch,The Pulley ShakeSearch Take-home Challenge,70
16,metersphere / metersphere,An open source continuous testing platform. Me...,674
17,wangdoc / ssh-tutorial,SSH 教程,66
18,mytechnotalent / Reverse-Engineering-Tutorial,A comprehensive reverse engineering tutorial c...,115
19,tiangolo / fastapi,"FastAPI framework, high performance, easy to l...","1,668"
20,PaddlePaddle / PaddleOCR,Awesome multilingual OCR toolkits based on Pad...,"1,483"
21,yamashi / PerformanceOverhaulCyberpunk,"Performance boost, bug fixes and hacks for fun...",54
22,callstack / react-native-paper,Material Design for React Native (Android & iOS),"1,098"
23,mubix / solarflare,SolarWinds Orion Account Audit / Password Dump...,24
24,chanakaudaya / solutions-architecture-patterns,This repository contains solutions architectur...,99

##### 6. Scrape the details of top 100 songs on billboard.com.

In [5]:
# Function Definition
def billboard(url):
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating the empty lists for the data to be extracted.
    song_name = []
    artist_name = []
    last_week_rank = []
    peak_rank = []
    weeks_on_board = []
    
    # Reaching the charts option
    try:
        charts = driver.find_element_by_xpath("//ul[@class = 'header__link-list header__main-menu bg--dark']/li[1]/a")
        charts.click()
    except ElementNotInteractableException as e:
        driver.get(charts.get_attribute('href'))
    
    # Reaching the Hot 100 page.
    driver.find_element_by_xpath("//div[@class = 'site-header-links__contents bb-user-anon bb-user-free']/a[3]").click()
    
    # Extrating the required data
    # Song Name
    for i in driver.find_elements_by_xpath("//span[@class = 'chart-element__information__song text--truncate color--primary']"):
        song_name.append(i.text)
    # Artist Name
    for i in driver.find_elements_by_xpath("//span[@class = 'chart-element__information__artist text--truncate color--secondary']"):
        artist_name.append(i.text)
    # Last Week Rank
    for i in driver.find_elements_by_xpath("//div[@class = 'chart-element__meta text--center color--secondary text--last']"):
        last_week_rank.append(i.text)
    # Peak Rank
    for i in driver.find_elements_by_xpath("//div[@class = 'chart-element__meta text--center color--secondary text--peak']"):
        peak_rank.append(i.text)
    # Weeks on Board
    for i in driver.find_elements_by_xpath("//div[@class = 'chart-element__meta text--center color--secondary text--week']"):
        weeks_on_board.append(i.text)
    
    # Creating the dataframe.
    songs_df = pd.DataFrame({"Song Name" : song_name,
                             "Artist Name" : artist_name,
                             "Last Week Rank" : last_week_rank,
                             "Peak Rank" : peak_rank,
                             "Weeks On Board" : weeks_on_board})
    return songs_df


# Calling the function.
billboard("https://www.billboard.com/")

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks On Board
0,Mood,24kGoldn Featuring iann dior,2,1,17
1,All I Want For Christmas Is You,Mariah Carey,14,1,40
2,Positions,Ariana Grande,4,1,6
3,Rockin' Around The Christmas Tree,Brenda Lee,21,2,35
4,Dakiti,Bad Bunny & Jhay Cortez,15,5,5
...,...,...,...,...,...
95,Back To The Streets,Saweetie Featuring Jhene Aiko,85,76,3
96,Martin & Gina,Polo G,89,61,18
97,Hole In The Bottle,Kelsea Ballerini,87,72,8
98,So Done,The Kid LAROI,100,59,6
99,Bichota,Karol G,97,97,2

##### 8. Scrape the details of Highest selling novels.

In [6]:
# Function Definition
def books(url):
    driver =  webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating empty lists for the data to be extracted.
    book_name = []
    author_name = []
    vol_sold = []
    publisher = []
    genre = []
    
    # Extracting the required data.
    list_of_data = [book_name, author_name, vol_sold, publisher, genre]
    for x in range(1,6):
        for i in driver.find_elements_by_xpath("//tbody/tr/td[" + str(x) + "]"):
            list_of_data[x-1].append(i.text)

    # Creating the DataFrame of the extracted data.
    df_best_selling = pd.DataFrame({"Book Name" : list_of_data[0],
                                    "Author Name" : list_of_data[1],
                                    "Volumes Sold" : list_of_data[2],
                                    "Publisher" : list_of_data[3],
                                    "Genre" : list_of_data[4]})
    return df_best_selling
    
    

# Calling the function
books("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House
...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin

##### 9. Scrape the details most watched tv series of all time from imdb.com.

In [7]:
# Function Definition
def tv_shows(url):
    driver =  webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")
    driver.get(url)
    
    # Creating empty lists for the data to be extracted.
    name = []
    year_span = []
    genre = []
    runtime = []
    ratings = []
    votes = []
    
    # Extracting the required data.
    # TV Show Name
    for i in driver.find_elements_by_xpath("//h3[@class = 'lister-item-header']/a"):
        name.append(i.text)
    # Year Span
    for i in driver.find_elements_by_xpath("//span[@class = 'lister-item-year text-muted unbold']"):
        year_span.append(i.text)
    # Genre
    for i in driver.find_elements_by_xpath("//span[@class = 'genre']"):
        genre.append(i.text)
    # Runtime
    for i in driver.find_elements_by_xpath("//span[@class = 'runtime']"):
        runtime.append(i.text)
    # Ratings
    for i in driver.find_elements_by_xpath("//div[@class = 'ipl-rating-star small']/span[2]"):
        ratings.append(i.text)
    # Votes
    for i in driver.find_elements_by_xpath("//span[@name = 'nv']"):
        votes.append(i.text)
    # Creating the DataFrame of the extracted data.
    
    df_tv_shows = pd.DataFrame({"Name" : name,
                                "Year Span" : year_span,
                                "Genre" : genre,
                                "Runtime" : runtime,
                                "Ratings" : ratings,
                                "Votes" : votes})
    return df_tv_shows
    
    

# Calling the function
tv_shows("https://www.imdb.com/list/ls095964455/")

,Name,Year Span,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,738,239"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.8,"796,761"
2,The Walking Dead,(2010– ),"Drama, Horror, Thriller",44 min,8.2,"842,353"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"252,297"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"211,571"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"42,904"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"53,085"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"157,529"
98,Scream: The TV Series,(2015– ),"Crime, Drama, Horror",45 min,7.2,"33,659"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"176,423"

##### 10. Details of Datasets from UCI machine learning repositories.

In [2]:
# Function Definition
def uci(url):
    driver = webdriver.Chrome(r"F:\sanss_data\FlipRobo\chromedriver.exe")#, options=chrome_options)
    driver.get(url)
    time.sleep(3)
    
    # Reaching View all datasets
    driver.find_element_by_xpath("//tbody/tr/td[2]/span[2]/a").click()
    time.sleep(3)
    
    # Creating the empty lists of the required data.
    dataset_name = []
    data_type = []
    task = []
    attr_type = []
    no_of_inst = []
    no_of_attr = []
    year = []
    
    # Creating a list of all the empty lists in order to extract the data  required.
    data_list = [dataset_name, data_type, task, attr_type, no_of_inst, no_of_attr, year]
    
    # Extracting the data
    for x in range(1,8):
        for i in driver.find_elements_by_xpath("//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td["+ str(x) +"]"):
            data_list[x-1].append(i.text)
            
    # Creating dataframe
    df_datasets = pd.DataFrame({"Dataset Name" : data_list[0][1:560],
                                "Data type" : data_list[1][1:560],
                                "Task" : data_list[2][1:560],
                                "Attribute Type" : data_list[3][1:560],
                                "Number of Instances" : data_list[4][1:560],
                                "Number of Attribute" : data_list[5][1:560],
                                "Year" : data_list[6][1:560]})
    return df_datasets


# CAlling Function
uci("https://archive.ics.uci.edu/")

,Dataset Name,Data type,Task,Attribute Type,Number of Instances,Number of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
554,IIWA14-R820-Gazebo-Dataset-10Trajectories,,Regression,Integer,,,2020
555,Guitar Chords finger positions,Text,Classification,,2633,5,2020
556,Russian Corpus of Biographical Texts,Text,Classification,,200,2,2020
557,Codon usage,Multivariate,"Classification, Clustering",,13028,69,2020
558,Intelligent Media Accelerometer and Gyroscop...,Time-Series,Classification,Real,800,9,2020